# Generated by Django 4.2.6 on 2023-10-10 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mobileapps', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapp',
            name='app_download_link',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserAppSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_os', models.CharField(choices=[('iOS', 'iOS'), ('Android', 'Android')], max_length=10)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mobileapps.mobileapp')),
            ],
        ),
        migrations.CreateModel(
            name='Screenshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firebase_storage_url', models.URLField()),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screenshot_entries', to='mobileapps.mobileapp')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('comment', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_entries', to='mobileapps.mobileapp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='reviews',
            field=models.ManyToManyField(blank=True, to='mobileapps.review'),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='screenshots',
            field=models.ManyToManyField(blank=True, to='mobileapps.screenshot'),
        ),
    ]
