# Generated by Django 4.2.6 on 2023-10-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapps', '0002_mobileapp_app_download_link_userappselection_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='screenshot',
            name='app',
        ),
    ]
