# Generated by Django 4.2.6 on 2023-10-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapps', '0005_mobileapp_os_logos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mobileapp',
            name='app_download_link',
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='android_download_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='ios_download_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
