# Generated by Django 4.2.6 on 2023-10-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapps', '0006_remove_mobileapp_app_download_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapp',
            name='linux_download_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='macos_download_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='windows_download_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
