# Generated by Django 4.2.6 on 2023-10-10 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapps', '0007_mobileapp_linux_download_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapp',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='version',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
