# Generated by Django 4.2.6 on 2023-10-11 10:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapps', '0008_mobileapp_release_date_mobileapp_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapp',
            name='appGalleryUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='app_image',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='category',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='dataSafety',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='featureImage',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='highlightsDescrition1',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='highlightsDescrition2',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='highlightsDescrition3',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='highlightsIcon1',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='highlightsIcon2',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='highlightsIcon3',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='highlightsTitle1',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='highlightsTitle2',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='highlightsTitle3',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='installs',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='longDescription',
            field=models.TextField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='phoneImage',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='playStoreUrl',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='privacyPolicyUrl',
            field=models.URLField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='rating',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='shortDescription',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mobileapp',
            name='shortIDescription',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='icon',
            field=models.URLField(),
        ),
    ]
