# Generated by Django 4.2.6 on 2023-10-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobileapps', '0009_mobileapp_appgalleryurl_mobileapp_app_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobileapp',
            name='whatsNew',
            field=models.CharField(default='nothing', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='dataSafety',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='mobileapp',
            name='shortIDescription',
            field=models.CharField(max_length=200),
        ),
    ]
